import 'package:mychat/features/chat/data/models/chat_model.dart';

List<ChatModel> listOfcontacts = [
  //list of contacts
  ChatModel(
    id: 1,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
    status: "'A full stack developer'",
  ),
  ChatModel(
    id: 2,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
    status: "'A full stack developer'",
  ),
  ChatModel(
    id: 3,
    name: "felam Doe",
    icon: "assets/images/group1.jpg",
    isGroup: true,
    time: "10:00",
    currentMessage: "Hello everyone",
    status: 'Mobile developer',
  ),
  ChatModel(
    id: 4,
    name: "jane alex",
    icon: "assets/images/group2.jpg",
    isGroup: true,
    time: "9:00",
    currentMessage: "Hey, I am good",
    status: 'A full stack developer',
  ),
  ChatModel(
    id: 5,
    name: "bon Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
    status: "front end developer",
  ),
  ChatModel(
    id: 6,
    name: "fj vjj",
    icon: "assets/images/group2.jpg",
    isGroup: true,
    time: "9:00",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 7,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
    status: 'A full stack developer',

  ),
  ChatModel(
    id: 8,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 9,
    name: "kdfj Doe",
    icon: "assets/images/group1.jpg",
    isGroup: true,
    time: "10:00",
    currentMessage: "Hello everyone",
  ),
  ChatModel(
    id: 10,
    name: "ababa jaja",
    icon: "assets/images/group2.jpg",
    isGroup: true,
    time: "9:00",
    currentMessage: "Hey, I am good",
    status: 'A full stack developer',

  ),
  ChatModel(
    id: 11,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
    status: 'A full stack developer',

  ),
  ChatModel(
    id: 12,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
    status: 'A full stack developer',
  ),
];
