import 'package:mychat/features/chat/data/models/chat_model.dart';

List<ChatModel> listOfChats = [
  ChatModel(
    id: 1,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
  ),
  ChatModel(
    id: 2,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 3,
    name: "Group 1",
    icon: "assets/images/group1.jpg",
    isGroup: true,
    time: "10:00",
    currentMessage: "Hello everyone",
  ),
  ChatModel(
    id: 4,
    name: "Group 2",
    icon: "assets/images/group2.jpg",
    isGroup: true,
    time: "9:00",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 5,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
  ),
  ChatModel(
    id: 6,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 7,
    name: "Group 1",
    icon: "assets/images/group1.jpg",
    isGroup: true,
    time: "10:00",
    currentMessage: "Hello everyone",
  ),
  ChatModel(
    id: 8,
    name: "Group 2",
    icon: "assets/images/group2.jpg",
    isGroup: true,
    time: "9:00",
    currentMessage: "Hey, I am good",
  ),
  ChatModel(
    id: 9,
    name: "John Doe",
    icon: "assets/images/user1.jpg",
    isGroup: false,
    time: "Now",
    currentMessage: "Hello there, how are you?",
  ),
  ChatModel(
    id: 10,
    name: "Jane Doe",
    icon: "assets/images/user2.jpg",
    isGroup: false,
    time: "2:30",
    currentMessage: "Hey, I am good",
  ),
];
